# Generated by Django 5.2.1 on 2025-05-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('staff', 'Сотрудник')], default='staff', max_length=20),
        ),
    ]
