# Generated by Django 5.2.1 on 2025-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=False, verbose_name='Получать уведомления на email'),
        ),
    ]
