# Generated by Django 5.2.1 on 2025-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_documentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_document', 'Новый документ'), ('new_comment', 'Новый комментарий')], default='new_document', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('edit', 'Редактирование'), ('sign', 'Подписание'), ('comment', 'Комментарий')], max_length=10),
        ),
    ]
