# Generated by Django 5.2.1 on 2025-05-23 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='recipient',
        ),
        migrations.AddField(
            model_name='document',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
