# Generated by Django 5.2.1 on 2025-05-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_remove_document_recipient_document_recipients'),
    ]

    operations = [
    ]
